### PR TITLE
Add AC's plates metadata

### PR DESCRIPTION
**Pull request by ACColin**
Adding 142 rows in metadata file for all terminal taxa of sections Adnataria and Exsertaria sampled at CCA.
Sequenced on S4 flowcell.

### CODE REVIEW

**Comment by kdm9** [comment]
Sorry AC but it looks like Excel has done some strange things to the character encoding. Would you mind re-saving it as a UTF8-encoded tsv?

It also seems like excel has added a lot of quotes and has truncated the precision of many numbers (both of which are fine) which complicates the diff a lot.

**Comment by ACColin** [comment]
[sample-metadata.txt](https://github.com/kdm9/Paneuc-acanthophis/files/8606344/sample-metadata.txt)

Argh sorry! I downloaded it again, edit in excel and saved as UTF-8 .tsv. I hope it's good!

**Comment by kdm9** [comment]
Hi AC,

Great, thanks, that solved the immediate issue. Now, there are a few more issues:

- some of your CCA samples are duplicated from the CCA 1&2 plates. I.e. each sample ID should only be in there once
- Many of the dates have changed. Not sure why but it looks like excel has buggered with the dates. I *think* it's mostly changing formats (which is fine, but not ideal), but double check them please.

Cheers,
K

**Comment by ACColin** [comment]
I think I have a solution for both:
- because I wasn't sure about how Acanthophis deals with duplicate sample names, in the raw fastqs folder '2021-08_Colin_novaseq_S4/' I created a softlink for each one of the samples to name them novaseq_CCAXXXX instead of CCAXXXX and created the samplelist with the novaseq_ prefix. Probably not the best approach, but that's all that came to my mind at the time. I can replace my sample names and add the prefix in sample-metadata.tsv which would work to call the samples with Acanthophis and solve the duplicate issue.
- for the dates instead of Excel I'll use Notepad++ to edit, which should solve the problem.
What do you think? Let me know if you think there is a better approach to this.

Cheers,
AC

**Pull request closed without merging**
